---
title: "README"
output: github_document
---

# R Programming

In this sub-folder you will find some of my work creating functions to analize data eficiently, the folders here contain the following items:

## Cache function:

Here you will find an example of a function that stores a computational result for later use if the same input is given. Cache functions are function that are able to cache potentially time-consuming computations.

## Hospital quality compare functions:

Here you will find an example of functions to analize the data from Hospital Compare web site (http://hospitalcompare.hhs.gov) run by the U.S. Department of Health and Human Services. In this folder you will found some functions that will help to find some specific information from the hospitals around the US and ranking them in diferents ways:

* Plot the U.S Hospitals 30-day mortality rates for heart attack
* Finding the best hospital in a state based on the number of cases of:

  - Heart attack
  - Heart failure
  - Pneumonia
  
* Ranking Hospitals in a specific state based on the number of cases of:

  - Heart attack
  - Heart failure
  - Pneumonia

* Ranking all Hospitals in all states based on their ranking place in their respective states and by the number of cases of:

  - Heart attack
  - Heart failure
  - Pneumonia