# Libraries loading
library(leaflet)
library(dplyr)
library(leafpop)

# Writing map variables

## Venezuela National Parks names
name_np<- c("Henri Pittier",
            "Sierra Nevada",
            "Guatopo",
            "Waraira Repano",
            "Yurubí",
            "Canaima",
            "Yacambú",
            "Cueva de la Quebrada del Toro",
            "Archipiélago de Los Roques",
            "Macarao",
            "Mochima",
            "Laguna de La Restinga",
            "Los Médanos de Coro",
            "Laguna de Tacarigua",
            "Cerro El Copey - Jóvito Villalba",
            "Aguaro-Guariquito",
            "Morrocoy",
            "El Guácharo",
            "Terepaima",
            "Jaua-Sarisariñama	Flag of Bolívar State.svg",
            "Serranía La Neblina",
            "Cerro Yapacana",
            "Duida-Marahuaca",
            "Península de Paria",
            "Sierra de Perijá",
            "El Tamá",
            "San Esteban",
            "Juan Crisóstomo Falcón",
            "Santos Luzardo",
            "Guaramacal",
            "Dinira",
            "General Juan Pablo Peñaloza",
            "Chorro El Indio",
            "Sierra de La Culata",
            "Cerro Saroche",
            "Turuépano",
            "Mariusa",
            "Ciénagas del Catatumbo",
            "Parima-Tapirapeco",
            "Río Viejo-San Camilo",
            "El Guache",
            "Tapo-Caparo")
## Venezuela National Parks areas (Km^2)
area_np<-c(1078.00,
           2764.46,
           1224.64,
           851.92,
           236.70,
           30000,
           269.16,
           48.85,
           2211.20,
           150,
           949.35,
           188.62,
           912.80,
           391,
           71.30,
           5690,
           320.90,
           627,
           186.5,
           3300,
           13600,
           3200,
           3737.4,
           375,
           2952.88,
           1390,
           445,
           200,
           5843.68,
           214.66,
           453.28,
           952,
           170,
           2004,
           322.94,
           726,
           3310,
           2261.3,
           3900,
           800,
           125,
           2050)

## venezuela National Parks coordenates in decimals:
lat <- c(10.38,
         8.566667,
         10.076361,
         10.583,
         10.47875,
         5.499583,
         9.690778,
         10.831972,
         11.8125,
         10.401833,
         10.306028,
         10.982833,
         11.442583,
         10.271194,
         11.008278,
         8.370639,
         10.830889,
         10.133833,
         9.866861,
         5.008,
         1.244778,
         3.813944,
         3.620444,
         10.703611,
         9.390972,
         7.540444,
         10.396083,
         11.223361,
         6.720778,
         9.180111,
         9.430472,
         7.883306,
         7.94025,
         8.914667,
         10.521667,
         10.471667,
         9.392972,
         9.308028,
         1.939306,
         7.168333,
         9.572389,
         8.148722
)

lng <- c(-67.618889,
         -70.7,
         -66.416528,
         -66.583361,
         -68.65925,
         -62.000028,
         -69.59275,
         -69.013778,
         -66.741917,
         -67.1775,
         -64.479194,
         -64.149944,
         -69.675111,
         -65.862361,
         -63.896556,
         -66.712917,
         -68.262389,
         -63.354167,
         -69.275583,
         -64.148111,
         -65.6655,
         -66.712917,
         -65.570194,
         -62.463139,
         -72.993306,
         -72.187194,
         -67.964278,
         -69.549889,
         -67.570833,
         -70.217972,
         -70.169472,
         -72.074083,
         -71.809694,
         -71.144833,
         -69.621111,
         -62.896889,
         -61.449111,
         -72.188778,
         -64.71625,
         -71.430083,
         -69.5615,
         -71.14375
)


## Venezuela National Parks popup information URLs:
np_info <- c(
  "https://es.wikipedia.org/wiki/Parque_nacional_Henri_Pittier",
  "https://es.wikipedia.org/wiki/Parque_nacional_Sierra_Nevada_(Venezuela)",
  "https://es.wikipedia.org/wiki/Parque_nacional_Guatopo",
  "https://es.wikipedia.org/wiki/Parque_nacional_Waraira_Repano",
  "https://es.wikipedia.org/wiki/Parque_nacional_Yurub%C3%AD",
  "https://es.wikipedia.org/wiki/Parque_nacional_Canaima",
  "https://es.wikipedia.org/wiki/Parque_nacional_Yacamb%C3%BA",
  "https://es.wikipedia.org/wiki/Parque_nacional_Cueva_de_la_Quebrada_del_Toro",
  "https://es.wikipedia.org/wiki/Parque_nacional_Archipi%C3%A9lago_de_Los_Roques",
  "https://es.wikipedia.org/wiki/Parque_nacional_Macarao",
  "https://es.wikipedia.org/wiki/Parque_nacional_Mochima",
  "https://es.wikipedia.org/wiki/Parque_nacional_Laguna_de_La_Restinga",
  "https://es.wikipedia.org/wiki/Parque_nacional_Los_M%C3%A9danos_de_Coro",
  "https://es.wikipedia.org/wiki/Parque_nacional_Laguna_de_Tacarigua",
  "https://es.wikipedia.org/wiki/Parque_nacional_Cerro_El_Copey_-_J%C3%B3vito_Villalba",
  "https://es.wikipedia.org/wiki/Parque_nacional_Aguaro-Guariquito",
  "https://es.wikipedia.org/wiki/Parque_nacional_Morrocoy",
  "https://es.wikipedia.org/wiki/Parque_nacional_El_Gu%C3%A1charo",
  "https://es.wikipedia.org/wiki/Parque_nacional_Terepaima",
  "https://es.wikipedia.org/wiki/Parque_nacional_Jaua-Sarisari%C3%B1ama",
  "https://es.wikipedia.org/wiki/Parque_nacional_Serran%C3%ADa_La_Neblina",
  "https://es.wikipedia.org/wiki/Parque_nacional_Cerro_Yapacana",
  "https://es.wikipedia.org/wiki/Parque_nacional_Duida-Marahuaca",
  "https://es.wikipedia.org/wiki/Parque_nacional_Pen%C3%ADnsula_de_Paria",
  "https://es.wikipedia.org/wiki/Parque_nacional_Sierra_de_Perij%C3%A1",
  "https://es.wikipedia.org/wiki/Parque_nacional_El_Tam%C3%A1",
  "https://es.wikipedia.org/wiki/Parque_nacional_San_Esteban",
  "https://es.wikipedia.org/wiki/Parque_nacional_Juan_Cris%C3%B3stomo_Falc%C3%B3n",
  "https://es.wikipedia.org/wiki/Parque_nacional_Santos_Luzardo",
  "https://es.wikipedia.org/wiki/Parque_nacional_Guaramacal",
  "https://es.wikipedia.org/wiki/Parque_nacional_Dinira",
  "https://es.wikipedia.org/wiki/Parque_nacional_General_Juan_Pablo_Pe%C3%B1aloza",
  "https://es.wikipedia.org/wiki/Parque_nacional_Chorro_El_Indio",
  "https://es.wikipedia.org/wiki/Parque_nacional_Sierra_de_La_Culata",
  "https://es.wikipedia.org/wiki/Parque_nacional_Cerro_Saroche",
  "https://es.wikipedia.org/wiki/Parque_nacional_Turu%C3%A9pano",
  "https://es.wikipedia.org/wiki/Parque_nacional_Mariusa",
  "https://es.wikipedia.org/wiki/Parque_nacional_Ci%C3%A9nagas_del_Catatumbo",
  "https://es.wikipedia.org/wiki/Parque_nacional_Parima-Tapirapeco",
  "https://es.wikipedia.org/wiki/Parque_nacional_R%C3%ADo_Viejo-San_Camilo",
  "https://es.wikipedia.org/wiki/Parque_nacional_El_Guache",
  "https://es.wikipedia.org/wiki/Parque_nacional_Tapo-Caparo"
)

## Venezuela National Parks Images URLs:

np_img<- c(
"https://upload.wikimedia.org/wikipedia/commons/2/28/Parque_Nacional_Henri_Pittier.JPG",
"https://upload.wikimedia.org/wikipedia/commons/1/10/CarreteraPicoElAguila.jpg",
"https://upload.wikimedia.org/wikipedia/commons/1/1e/Parque_Nacional_Guatopo_Gu%C3%A1rico.jpg",
"https://upload.wikimedia.org/wikipedia/commons/e/ee/Cerro_El_Avila.jpg",
"https://upload.wikimedia.org/wikipedia/commons/5/5c/Bajo_la_Cascada.jpg",
"https://upload.wikimedia.org/wikipedia/commons/f/fd/Kukenan_Tepuy_at_Sunset.jpg",
"https://upload.wikimedia.org/wikipedia/commons/9/92/Cascada_Parque_Yacambu.JPG",
"https://upload.wikimedia.org/wikipedia/commons/1/10/Parque_Nacional_Cueva_de_la_Quebrada_del_Toro.jpg",
"https://upload.wikimedia.org/wikipedia/commons/0/04/Cayo_Francisqui_apacible.JPG",
"https://upload.wikimedia.org/wikipedia/commons/5/5d/Extenciones_de_monta%C3%B1a_que_protejen_la_cordillera_de_la_costa.jpg",
"https://upload.wikimedia.org/wikipedia/commons/e/ea/Mochima.jpg",
"https://upload.wikimedia.org/wikipedia/commons/4/48/Laguna_de_La_Restinga_National_Park_2.jpg",
"https://upload.wikimedia.org/wikipedia/commons/0/0f/MedanosdeCoro.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/6f/Tacarigua_Lagoon_National_Park_-_Parque_Nacional_Laguna_de_Tacarigua_%2810296002123%29.jpg",
"https://upload.wikimedia.org/wikipedia/commons/5/5a/San_Juan_Valley.jpg",
"https://upload.wikimedia.org/wikipedia/commons/f/fa/Pozo_La_Zorra_Parque_Nacional_Aguaro_Guariquito.jpg",
"https://upload.wikimedia.org/wikipedia/commons/e/e2/Cocotero_en_Cayo_Sombrero.jpg",
"https://upload.wikimedia.org/wikipedia/commons/7/7a/La_Cueva_del_Guacharo.jpg",
"https://upload.wikimedia.org/wikipedia/commons/e/e3/Pozo_de_agua_en_el_Parque_Nacional_Terepaima.jpg",
"http://misadventuresmag.com/wp-content/uploads/2014/03/Sarisarinama.jpg",
"https://upload.wikimedia.org/wikipedia/commons/b/b7/Pico_da_Neblina.jpg",
"https://upload.wikimedia.org/wikipedia/commons/2/25/Copia_de_Puerto_Atabapo_43._2006.jpg",
"https://upload.wikimedia.org/wikipedia/commons/9/93/Cerro_Duida.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/64/Playa_Medina_Peninsula_Paria.jpg",
"https://upload.wikimedia.org/wikipedia/commons/1/1d/Conquistando_la_Sierra_de_Perij%C3%A1.jpg",
"https://upload.wikimedia.org/wikipedia/commons/1/15/Cerro_el_Cobre.jpg",
"https://upload.wikimedia.org/wikipedia/commons/b/b7/Monta%C3%B1as_que_se_unen_a_la_cordillera_de_la_costa.jpg",
"https://upload.wikimedia.org/wikipedia/commons/8/8b/Cataratas_del_Hueque_%282%29.JPG",
"https://upload.wikimedia.org/wikipedia/commons/f/f2/Extensas_llanuras_de_vegetaci%C3%B3n_sabanera.jpg",
"https://upload.wikimedia.org/wikipedia/commons/f/f2/Laguna_de_los_Cedros_III.JPG",
"https://i.pinimg.com/originals/15/aa/1c/15aa1c86d5616ebf792937d188336f45.jpg",
"https://upload.wikimedia.org/wikipedia/commons/e/ef/Lagunas_y_monta%C3%B1as_del_parque_nacional_general_juan_pablo_pe%C3%B1aloza_paramo_batallon_14.jpg",
"https://upload.wikimedia.org/wikipedia/commons/5/5d/Valles_en_sector_Loma_de_Viento.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/64/Lagunas_%28Sierra_de_la_Culata%29.jpg",
"https://www.ivenezuela.travel/wp-content/uploads/2016/12/parque_nacional_cerro_saroche.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/65/Puerto_Aj%C3%ADes.jpg",
"https://upload.wikimedia.org/wikipedia/commons/6/61/Delta_del_Orinoco_110514-1.JPG",
"https://upload.wikimedia.org/wikipedia/commons/b/b6/Catatumbolightning.jpg",
"https://upload.wikimedia.org/wikipedia/commons/d/dd/Bongo_autana.jpg",
"https://upload.wikimedia.org/wikipedia/commons/2/21/For%C3%AAt_gallerie.jpg",
"https://upload.wikimedia.org/wikipedia/commons/5/56/CHORRO_SAN_MIGUEL_-_PORTUGUESA_-_OSPINO.JPG",
"https://upload.wikimedia.org/wikipedia/commons/0/06/Cascada_El_Amor.jpg"
)

## Venezuela National Parks data frame:
ven_np_df <- data.frame(name = name_np,
                        area = area_np,
                        lat = lat,
                        lng = lng,
                        info = np_info,
                        img = np_img)
